# Generated by Django 3.2.8 on 2021-10-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bills',
            new_name='Bill',
        ),
        migrations.RenameModel(
            old_name='BillDetails',
            new_name='BillDetail',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
