# Generated by Django 3.2.8 on 2021-10-31 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20211030_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itme_rate',
            new_name='item_rate',
        ),
    ]
