# Generated by Django 3.2.8 on 2021-11-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_rename_itme_rate_item_item_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.customer'),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill'),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.item'),
        ),
    ]
