# Generated by Django 3.2.8 on 2021-11-09 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_billdetail_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdetail',
            name='item_quantity',
        ),
    ]
