# Generated by Django 3.2.8 on 2021-11-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_remove_billdetail_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='item_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
