# Generated by Django 3.2.8 on 2021-11-09 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_billdetail_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill', unique=True),
        ),
    ]
