# Generated by Django 3.2.8 on 2021-11-17 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0014_alter_billdetail_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bills.customer'),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bills.bill'),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bills.item'),
        ),
    ]
